export const settings = {
  GOOGLE_API_KEY: Bun.env.GOOGLE_API_KEY,
  MODEL: Bun.env.MODEL,
  AZURE_DEVOPS_DEFAULT_PROJECT: Bun.env.AZURE_DEVOPS_DEFAULT_PROJECT,
  AZURE_DEVOPS_PAT: Bun.env.AZURE_DEVOPS_PAT,
  AZURE_DEVOPS_ORG_URL: Bun.env.AZURE_DEVOPS_ORG_URL,
  AZURE_DEVOPS_SPRINT_PATH: Bun.env.AZURE_DEVOPS_SPRINT_PATH,
  GITHUB_PAT: Bun.env.GITHUB_PAT,
  XAI_API_KEY: Bun.env.XAI_API_KEY
}

const models = ['gemini-2.5-flash-preview-05-20', 'grok-3']

